# src/llm/generator.py

from src.llm.client import GeminiClient
from src.services.prompt_loader import load_prompt


class NoteGenerator:
    """Generate notes from transcripts."""

    def __init__(self) -> None:
        self.client = GeminiClient()

    def generate(
        self,
        transcript: str,
        note_style: str,
    ) -> str:
        """
        Generate Markdown notes.

        Args:
            transcript: Raw transcript.
            note_style: Selected note style.

        Returns:
            Markdown generated by Gemini.
        """

        template = load_prompt(note_style)

        prompt = template.replace(
            "{{transcript}}",
            transcript,
        )

        markdown = self.client.generate(prompt)

        return markdown

